language: ruby

rvm:
  - 2.2.4

branches:
 only:
 - master
 - develop
 - satellite-6.2
 - openshift3

notifications:
 email: false

install: ./.travis.sh install

before_script: ./.travis.sh migrate

script:
 - gem install rubocop -v 0.35.1 && rubocop
 - pushd ../foreman && rake test:fusor && popd
 - ./.travis.sh ember-run

services:
  - postgresql
