:fusor:
  :provision:
    :sleep_before_reboot: "60"

  :content:
    :content_view:
      :composite_view_name: "Fusor Deployment"
      :rpm_component_view_name: "Fusor RPM Content"
      :puppet_component_view_name: "Fusor Puppet Content"

    :rhev:
      - :product_name: "Red Hat Enterprise Linux Server"
        :repository_set_name: "Red Hat Enterprise Linux 6 Server (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

      - :product_name: "Red Hat Enterprise Linux Server"
        :repository_set_name: "Red Hat Enterprise Linux 6 Server (Kickstart)"
        :basearch: "x86_64"
        :releasever: "6.7"

      - :product_name: "Red Hat Enterprise Linux Server"
        :repository_set_name: "Red Hat Satellite Tools 6.1 (for RHEL 6 Server) (RPMs)"
        :basearch: "x86_64"

      - :product_name: "Red Hat Enterprise Linux Server"
        :repository_set_name: "Red Hat Enterprise Linux 6 Server - Supplementary (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

      - :product_name: "Red Hat Enterprise Virtualization"
        :repository_set_name: "Red Hat Enterprise Virtualization Management Agents (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

      - :product_name: "Red Hat Enterprise Virtualization"
        :repository_set_name: "Red Hat Enterprise Virtualization Manager 3.5 (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

      - :product_name: "JBoss Enterprise Application Platform"
        :repository_set_name: "JBoss Enterprise Application Platform 6 (RHEL 6 Server) (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

    :cloudforms:
      - :product_name: "Red Hat CloudForms"
        :repository_set_name: "Red Hat CloudForms Management Engine 5.3 (Files)"
        :basearch: "x86_64"
        #:image_file_name: "cfme-rhevm-5.3-54.x86_64.rhevm.ova" # Default behavior uses the 'latest' image file.

    :openstack:
      - :product_name: "Red Hat Enterprise Linux Server"
        :repository_set_name: "Red Hat Enterprise Linux 7 Server (RPMs)"
        :basearch: "x86_64"
        :releasever: "7Server"

      - :product_name: "Red Hat Enterprise Linux Server"
        :repository_set_name: "Red Hat Enterprise Linux 7 Server (Kickstart)"
        :basearch: "x86_64"
        :releasever: "7.1"

      - :product_name: "Red Hat Enterprise Linux Server"
        :repository_set_name: "Red Hat Enterprise Linux 7 Server - Extras (RPMs)"
        :basearch: "x86_64"

      - :product_name: "Red Hat Enterprise Linux Server"
        :repository_set_name: "Red Hat Enterprise Linux 7 Server - Optional (RPMs)"
        :basearch: "x86_64"
        :releasever: "7Server"

      - :product_name: "Red Hat Enterprise Linux Server"
        :repository_set_name: "Red Hat Enterprise Linux 7 Server - RH Common (RPMs)"
        :basearch: "x86_64"
        :releasever: "7Server"

      - :product_name: "Red Hat OpenStack"
        :repository_set_name: "Red Hat OpenStack 7.0 for RHEL 7 (RPMs)"
        :basearch: "x86_64"
        :releasever: "7Server"

      - :product_name: "Red Hat OpenStack"
        :repository_set_name: "Red Hat OpenStack 7.0 for RHEL 7 Platform director (RPMs)"
        :basearch: "x86_64"
        :releasever: "7Server"

      - :product_name: "Red Hat OpenStack"
        :repository_set_name: "Red Hat OpenStack 7.0 for RHEL 7 (Files)"
        :basearch: "x86_64"
        :releasever: "7Server"

      - :product_name: "Red Hat Software Collections for RHEL Server"
        :repository_set_name: "Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server"
        :basearch: "x86_64"
        :releasever: "7Server"

  :puppet_classes:
    - :name: "ovirt"
    - :name: "ovirt::engine::config"
    - :name: "ovirt::engine::packages"
    - :name: "ovirt::engine::setup"
    - :name: "ovirt::engine::import_template"
    - :name: "ovirt::engine::run_vm"
    - :name: "ovirt::hypervisor::packages"

  :host_groups:
    :rhev:
     :root_name: "Fusor Base" # seeded by the fusor-installer
     :host_groups:
       - :parent: "Fusor Base"

       - :name: "RHEV-Engine"
         :os: "RedHat"
         :major: "6"
         :minor: "7"
         :parent: :root_deployment
         :puppet_classes:
           - :name: "ovirt"
             :parameters:
             - :name: "product"
               :override: "RHEV"
           - :name: "ovirt::engine::config"
           - :name: "ovirt::engine::packages"
           - :name: "ovirt::engine::setup"
             :parameters:
             - :name: "firewall_manager"
               :override: "iptables"

       - :name: "RHEV-Hypervisor"
         :os: "RedHat"
         :major: "6"
         :minor: "7"
         :parent: :root_deployment
         :puppet_classes:
           - :name: "ovirt"
             :parameters:
             - :name: "product"
               :override: "RHEV"
           - :name: "ovirt::hypervisor::packages"
    :openstack:
     :root_name: "Fusor Base" # seeded by the fusor-installer
     :host_groups:
       - :parent: "Fusor Base"

       - :name: "OpenStack-Undercloud"
         :parent: :root_deployment
         :os: "RedHat"
         :major: "7"
         :minor: "1"

  :activation_key:
    :name: "Fusor_Key"
    :subscription_descriptions:
      - "Red Hat Cloud Infrastructure"

