:fusor:
  :content:
    :content_view:
      :composite_view_name: "Fusor Deployment"
      :rpm_component_view_name: "Fusor RPM Content"
      :puppet_component_view_name: "Fusor Puppet Content"

    :rhev:
      - :product_name: "Red Hat Enterprise Linux Server"
        :repository_set_name: "Red Hat Enterprise Linux 6 Server (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

      - :product_name: "Red Hat Enterprise Linux Server"
        :repository_set_name: "Red Hat Enterprise Linux 6 Server (Kickstart)"
        :basearch: "x86_64"
        :releasever: "6.6"

      - :product_name: "Red Hat Enterprise Linux Server"
        :repository_set_name: "Red Hat Enterprise Linux 6 Server - RH Common (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

      - :product_name: "Red Hat Enterprise Linux Server"
        :repository_set_name: "Red Hat Enterprise Linux 6 Server - Supplementary (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

      - :product_name: "Red Hat Enterprise Virtualization"
        :repository_set_name: "Red Hat Enterprise Virtualization Hypervisor (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

      - :product_name: "Red Hat Enterprise Virtualization"
        :repository_set_name: "Red Hat Enterprise Virtualization Management Agents (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

      - :product_name: "Red Hat Enterprise Virtualization"
        :repository_set_name: "Red Hat Enterprise Virtualization Manager 3.5 (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

      - :product_name: "JBoss Enterprise Application Platform"
        :repository_set_name: "JBoss Enterprise Application Platform 6 (RHEL 6 Server) (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

  :host_groups:
    :rhev:
     :root_name: "Fusor Base" # seeded by the fusor-installer
     :host_groups:
       - :parent: "Fusor Base"

       - :name: "RHEV-Engine"
         :parent: :root_deployment
         :puppet_classes:
           - :name: "ovirt"
             :parameters:
             - :name: "product"
               :override: "RHEV"
           - :name: "ovirt::engine::config"
             :parameters:
             - :name: "username"
             - :name: "dc_name"
             - :name: "cluster_name"
             - :name: "cpu_type"
             - :name: "host_name"
             - :name: "host_address"
             - :name: "root_password"
             - :name: "storage_name"
             - :name: "storage_address"
             - :name: "storage_path"
             - :name: "export_address"
             - :name: "export_name"
             - :name: "export_path"
             - :name: "storage_type"
             - :name: "share_path"
           - :name: "ovirt::engine::packages"
           - :name: "ovirt::engine::setup"
             :parameters:
             - :name: "application_mode"
             - :name: "storage_type"
             - :name: "organization"
             - :name: "nfs_config_enabled"
             - :name: "iso_domain_name"
             - :name: "iso_domain_mount_point"
             - :name: "admin_password"
             - :name: "db_user"
             - :name: "db_password"
             - :name: "db_host"
             - :name: "db_port"
             - :name: "storage_domain_dir"
             - :name: "firewall_manager"
               :override: "iptables"
             - :name: "url"
             - :name: "username"

       - :name: "RHEV-Hypervisor"
         :parent: :root_deployment
         :puppet_classes:
           - :name: "ovirt"
             :parameters:
             - :name: "product"
               :override: "RHEV"
           - :name: "ovirt::hypervisor::packages"

  :activation_key:
    :name: "Fusor_Key"
    :subscription_descriptions:
      - "Red Hat Cloud Infrastructure"

